name: TYZS3 OpenThread RCP
device: EFR32MG13P732F512GM48
base_project: src/openthread_rcp
filename: "{manifest_name}_{ot_rcp_version.split('/')[-1]}_gsdk_{sdk_version}_{baudrate}"
sdk: "gecko_sdk:4.4.6"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: openthread_rcp
  ot_rcp_version: dynamic
  baudrate: 230400

c_defines:
  SL_UARTDRV_USART_VCOM_PERIPHERAL: USART0
  SL_UARTDRV_USART_VCOM_PERIPHERAL_NO: 0
  SL_UARTDRV_USART_VCOM_BAUDRATE: 230400
  SL_UARTDRV_USART_VCOM_RX_BUFFER_SIZE: 64

  SL_UARTDRV_USART_VCOM_TX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_TX_PIN:  0

  SL_UARTDRV_USART_VCOM_RX_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RX_PIN:  1

  SL_UARTDRV_USART_VCOM_CTS_PORT: gpioPortF
  SL_UARTDRV_USART_VCOM_CTS_PIN:  4

  SL_UARTDRV_USART_VCOM_RTS_PORT: gpioPortA
  SL_UARTDRV_USART_VCOM_RTS_PIN:  2

  SL_UARTDRV_USART_VCOM_TX_LOC:  0
  SL_UARTDRV_USART_VCOM_RX_LOC:  0
  SL_UARTDRV_USART_VCOM_CTS_LOC: 0
  SL_UARTDRV_USART_VCOM_RTS_LOC: 0

  

